```{r, warning=FALSE, echo=FALSE}
source('R/init.R')
source('R/load_rna_dat.r')
```

```{r, warning=FALSE, echo=FALSE}
ggplot(patient_labels[!is.na(ca15_3)], aes(x = clinical_response, y = ca15_3)) +
 geom_boxplot() +
 scale_y_continuous(trans = 'log10') +
 facet_grid(~ arm)
thresh <- patient_labels[!is.na(ca15_3) & clinical_response == 'R', max(ca15_3)]

patient_labels[!is.na(ca15_3), .(sum(ca15_3 > thresh), sum(ca15_3 <= thresh))]
# patient_labels[!is.na(ca15_3), .(sum(ca15_3 > median(ca15_3)), sum(ca15_3 <= median(ca15_3)))]

```


# GSEA

```{r, warning=FALSE, echo=FALSE}
res <- readRDS(file = 'rds2/GSEA_ca15_3_baseline_TMM.rds')
# dplyr::filter(res, arm != 'All arms') %>%
res %>%
  plot_es(legend.position = 'right', ptitle = 'paired_hallmark_CA15_3',
          # filename = sprintf('plots2/%s/GSEA_%s.pdf',
          #                    format(Sys.time(), "%Y_%b_%d"), 'paired'),
          subset_var = NULL, x_var = 'arm')
```


# CA15.3 correlation with Danaher signatures

```{r, warning=FALSE, echo=FALSE}
## Investigate outlying patient
rna_sigs <- compute_RNA_sigs(sig = 'mmr_loss')
pat_id <- rna_sigs[which.max(FC), patient]
pat_id <- rna_sigs[which.max(FC), patient]
clinical_annotation[patient %in% pat_id]
```

```{r, warning=FALSE, echo=FALSE}
source('R/init.R')

plot_RNA_sig_MA(sig = 'mmr_loss') +
  scale_colour_gradient2(name = 'CA15.3',
                         trans = 'log10',
                         low = scales::muted('red'),
                         high = scales::muted('blue'),
                         na.value = 'white')
```

```{r, warning=FALSE, echo=FALSE}
source('R/init.R')
colour_var <- 'ca15_3'

plots <- lapply(danaher_signature_genes[, unique(signature_name)],
                function(sig) {
  plot_RNA_sig_MA(sig = sig, colour_var = colour_var) +
    scale_colour_gradient2(name = 'CA15.3',
                           trans = 'log10',
                           low = scales::muted('red'),
                           high = scales::muted('blue'),
                           na.value = 'white')
})

maartenutils::plot_panel_layout(plots, ncol = 2, nrow = 4,
  labels = NULL,
  plot_direct = F,
  ref_panel_idx = 2 * 8,
  clear_redundant_labels = T,
  clear_redundant_legends = T,
  filename = file.path(plot_dir, sprintf('ma_plot_%s.pdf', colour_var)),
  w = 17.4, h = 25, label_size = 8)
```

```{r, warning=FALSE, echo=FALSE}
source('R/init.R')
devtools::load_all(file.path('~/libs', 'GSEAgenesets'))
gene_sets <- filter_gmt(gmt_pat = 'h.all', gene_set_pat = '.')

colour_var <- 'ca15_3'
library(purrr)

plots <- imap(gene_sets, function(g, n) {
  p <- plot_RNA_sig_MA(sig = NULL, genes = g, colour_var = colour_var)
  p + scale_colour_gradient2(name = 'CA15.3',
                             trans = 'log10',
                             low = scales::muted('red'),
                             high = scales::muted('blue'),
                             na.value = 'white') +
    ggtitle(n)
})

maartenutils::plot_panel_layout(plots, ncol = 2, nrow = 4,
  labels = NULL,
  plot_direct = F,
  ref_panel_idx = 2 * 8,
  clear_redundant_labels = T,
  clear_redundant_legends = T,
  filename = file.path(plot_dir, sprintf('ma_plot_hallmark_%s.pdf', colour_var)),
  w = 17.4, h = 25, label_size = 8)
```
