---
title: "Identifying clinical responders from NanoString data in the TONIC trial"
author: "Maarten Slagter"
output: html_document
---

```{r, cache = F, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, cache = F, cache.lazy = F, 
                      cache.comments = F, autodep = T, warning = FALSE, 
                      echo = TRUE, error = FALSE)
knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
```

```{r, warning=FALSE, echo=FALSE, include=F}
source('R/load_data.R')
source('R/ML.R')
source('R/plotting.R')
library(maartenutils)
ggplot2::theme_set(theme_ms(base_size = 8))
```

# Naive/reference model performance

Naive model classification performance 
Classify according to response rate

```{r, warning=FALSE, echo=FALSE}
p <- mean(as.logical(responses))
p^2 + (1 - p)^2
2 * p * (1 - p)
curve(expr = x^2 + (1 - x)^2, from = 0, to = 1)
# curve(expr = 2 * x * (1 - x), from = 0, to = 1)
```

# PCA approach

Response seems to be partially explained by the first two principal components
on therapy samples.
For timepoints later than 1, we should probably be looking at fold changes
instead.

```{r, warning=FALSE, echo=FALSE}
ml_dat <- prepare_ml_dat(tp = 'On nivo')
plot_PCA_axes(tp = 'on_nivo', dat = ml_dat[[1]], color_var = 'response', 
              labellings = ml_dat[[2]])

ml_dat <- prepare_ml_dat(tp = 'Post-induction')
plot_PCA_axes(tp = 'post_induction', dat = ml_dat[[1]], color_var = 'response', 
              labellings = ml_dat[[2]])

ml_dat <- prepare_ml_dat(tp = 'Baseline')
plot_PCA_axes(tp = 'baseline', dat = ml_dat[[1]], color_var = 'response', 
              labellings = ml_dat[[2]])


setkey(patient_labels, filename)
ml_dat <- prepare_ml_dat(tp = 'Post-induction')
plot_PCA_axes(tp = 'post_induction', dat = ml_dat[[1]], color_var = 'arm', 
              labellings = patient_labels[rownames(ml_dat[[1]]), arm])

setkey(patient_labels, filename)
ml_dat <- prepare_ml_dat(tp = 'Baseline')
plot_PCA_axes(tp = 'baseline', dat = ml_dat[[1]], color_var = 'arm', 
              labellings = patient_labels[rownames(ml_dat[[1]]), arm])
```

# Glmnet approach

```{r, warning=FALSE, echo=FALSE}
glmnet_class_test(tp = 'Baseline')
```

```{r, warning=FALSE, echo=FALSE}
glmnet_class_test(tp = 'Post-induction')
```

```{r, warning=FALSE, echo=FALSE}
glmnet_class_test(tp = 'On nivo')
```

```{r, warning=FALSE, echo=FALSE}
res <- glmnet_class_test(tp = 'On nivo')
```

# Random forest approach

```{r, cache = T, dependson, warning=FALSE, echo=FALSE}
rfs <- plyr::llply(timepoints, function(tp) {
  perform_rf(tp = tp)
}, .parallel = !local_run)
```

```{r, warning=FALSE, echo=FALSE}
plots <- lapply(rfs, plot_importance)
plot_panel_layout(plots, ncol = 3, filename = NULL, 
                  w = 20, h = 20, label_size = 8)
```
