---
title: "NanoString data analyses in the TONIC trial"
author: "Maarten Slagter"
output:
  html_document:
    toc: true
    number_sections: true
    theme: united
---

```{r, cache = F, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(message = FALSE, cache = F, cache.lazy = F,
                      cache.comments = F, autodep = T, warning = FALSE,
                      echo = TRUE, error = FALSE)
knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
source('R/init.R')
```

# Parallel coordinates plots

## Geneset level

Which induction arms most strongly upregulate gene signatures associated with
response?

```{r, warning=FALSE, echo=FALSE}
source('R/plotting_adaptive.R')
source('R/plotting_nanostring.R')
source('R/test_associations.R')
colour_var = NULL
colour_var = 'patient'
colour_var = 'arm'
colour_var = 'response'
colour_var = 'clinical_response'

# debugonce(plot_parallel_coords_geneset)
# debugonce(prep_geneset_parallel_coords)
# debugonce(plot_parallel_coords)
plots <- lapply(danaher_scores.m[, auto_name(unique(variable))], function(x) {
  p <- plot_parallel_coords_geneset(x,
                                    colour_var = colour_var,
                                    facet_var = 'arm')
  return(p)
})
print(plots)
```

```{r, warning=FALSE, echo=FALSE}
source('R/plotting_adaptive.R')
source('R/plotting_nanostring.R')
source('R/test_associations.R')
# debugonce(plot_parallel_coords_geneset)
# debugonce(plot_parallel_coords)
for (sig in c('tis', 'ifn.gamma', 'cytotoxicity')) {
  plot_parallel_coords_geneset(sig, colour_var = colour_var, 
                               median_line_alpha = .8,
                               point_alpha = .35,
                               facet_var = 'arm')
  ggsave(file = file.path(plot_dir, sprintf('%s_parallel_coords.png', sig)), 
         width = 19, height = 10, units = 'cm')
}
```

```{r, warning=FALSE, echo=FALSE}
filename <- file.path(img_dir, sprintf('parallel_%s.pdf',
                                       ifelse(is.null(colour_var), 'ungrouped',
                                              colour_var)))

p <- maartenutils::plot_panel_layout(plots, ncol = 1, nrow = 3,
                                     filename = filename,
                                     labels = NULL,
                                     w = 22, h = 25,
                                     label_size = 8)
sys_file_open(filename)
```

```{r, eval = F, warning=FALSE, echo=FALSE}
source('R/plotting_nanostring.R')

gen_parallel_coord_plots <-
  function(facet_var = 'arm', colour_var = 'response') {
  plots <- lapply(danaher_scores.m[, auto_name(levels(variable))],
                  function(gene_set) {
                    browser()
    sum_dat <- prep_geneset_parallel_coords(gene_set = gene_set,
                                            colour_var = facet_var,
                                            facet_var = facet_var)
    p_dat <- danaher_scores.m[variable == gene_set]
    p <- plot_parallel_coords(p_dat = p_dat, sum_dat = sum_dat,
                              palette_name = 'FantasticFox',
                              facet_var = facet_var,
                              point_alpha = .6,
                              colour_var = colour_var, title = gene_set) +
      theme(legend.position = 'none')
    return(p)
  })

  filename <- file.path(img_dir, sprintf('parallel_%s.pdf',
                                         ifelse(is.null(colour_var), 'ungrouped',
                                                colour_var)))
  p <- maartenutils::plot_panel_layout(plots, ncol = 1, nrow = 4,
                                       filename = filename,
                                       labels = NULL,
                                       w = 22, h = 25)

  filename <- file.path(img_dir, sprintf('parallel_%s_highlighted.pdf',
                                         ifelse(is.null(colour_var), 'ungrouped',
                                                colour_var)))
  p <- maartenutils::plot_panel_layout(
    list(plots[['tis']], plots[['glycolytic.activity']]),
    ncol = 1, nrow = 2,
    filename = filename,
    labels = NULL,
    w = 22, h = 25 / 2)
  return(plots)
}

# plots <- gen_parallel_coord_plots(facet_var = 'arm', colour_var = 'patient')
plots <- gen_parallel_coord_plots(facet_var = 'arm', colour_var = 'response')
```

```{r, eval = F, warning=FALSE, echo=FALSE}
# source('R/init.R')
# source('R/plotting_adaptive.R')
# source('R/plotting_nanostring.R')
# devtools::load_all(file.path('~/libs', 'maartenutils'))
library(grid)
plot_panel_layout(lapply(sig_gene_sets, function(gs) {
                           p <- plot_parallel_coords_geneset(gene_set = gs)
                           if (gs != sig_gene_sets[1])
                             p <- p + ggplot2::theme(legend.position = 'none')
                           else
                             p <- p + ggplot2::theme(legend.position = 'right')
                           return(p)
                         }),
                  filename = file.path('plots', 'parallel_sig_signatures.pdf'),
                  labels = NULL,
                  w = 17.4, h = 25, ncol = 3)
```

# Heatmap of all values for response associated sigs

```{r, warning=FALSE, echo=FALSE}
source('R/plotting_adaptive.R')
source('R/plotting_nanostring.R')
source('R/test_associations.R')
t_dat <- test_gene_set_association(
  gene_set = danaher_scores.m[, levels(variable)], timepoint = 'On nivo')
# t_dat <- t_dat[log2FC > 0 & p_val <= 0.05]
# t_dat <- t_dat[p_val <= 0.05]
sig_gene_sets <- setdiff(t_dat[p_val <= 0.05, as.character(variable)], 
                         'mmr.loss')
setkey(t_dat, variable)
t_dat[gsub('_on.nivo', '', var_names)]
```

```{r, warning=FALSE, echo=FALSE}
var_names <- sprintf('%s_on.nivo', danaher_scores.m[, levels(variable)])
var_names <- sprintf('%s_on.nivo', sig_gene_sets)
p_dat <- danaher_scores[, c(var_names, 'patient'), with = F]
p_dat <- p_dat[complete.cases(p_dat)]
p_dat[, patient := sprintf('pat_%s', patient)]
p_dat <-
  controlled_merge(p_dat, patient_labels[, .(patient, arm, clinical_response)])

```

```{r, warning=FALSE, echo=FALSE, fig.width = 8, fig.height = 5}
graphics.off()
NMF::aheatmap(t(p_dat[, var_names, with = F]),
              scale = 'row',
              border_color = 'grey80',
              labRow = simple_cap(gsub('\\.', ' ',
                                       gsub('_on.nivo', '',
                                            gsub('pdl1', 'PD-L1', var_names))),
                                  caplist = c('cells', 'TIS', 'Th1')),
              labCol = p_dat[, patient],
              annRow = list('log2FC' = t_dat[gsub('_on.nivo', '', var_names),
                            log2FC]),
              annCol = list('Clinical response' = t(p_dat[,
                                                    clinical_response])),
                            # 'Induction arm' = t(p_dat[, arm])),
              annColors = list('Clinical response' =
                               tonic_color_palettes[['clinical_response']],
                               'Induction arm' =
                               tonic_color_palettes[['arm']]),
              width = 20/2.54, height = 10/2.54, 
              filename = file.path(plot_dir, 'heatmap_on_nivo.pdf'))
              # filename = NA)
t_dat
```

# Heatmaps of median FCs with and without p-values

```{r, warning=FALSE, echo=FALSE, fig.width = 9, fig.height = 12}
source('R/plotting_adaptive.R')
source('R/plotting_nanostring.R')
source('R/test_associations.R')
m <- rbindlist(lapply(auto_name(sig_gene_sets), function(gs) {
  test_gene_set_difference(gene_set = gs,
                           tp1 = 'Baseline',
                           tp = 'Post-induction')
}), fill = T)

invisible(m[p_val > .05, p_val := NA])
p <- plot_p_values_induction(m)
print(p)
ggsave(plot = p, filename = file.path(plot_dir,
                            'induction_fc_p_values_baseline_post_induction.png'),
       width = 10, height = 13, units = 'cm')
```

```{r, warning=FALSE, echo=FALSE, fig.width = 9, fig.height = 12}
invisible(m[, p_val := NA])
pa <- plot_p_values_induction(filter(m, arm != 'All arms'))
print(pa)
ggsave(plot = pa, filename = file.path(plot_dir,
                            'induction_fc_p_values_baseline_post_induction.png'),
       width = 10, height = 13, units = 'cm')
```

```{r, warning=FALSE, echo=FALSE, fig.width = 9, fig.height = 12}
m <- rbindlist(lapply(auto_name(sig_gene_sets), function(gs) {
  test_gene_set_difference(gene_set = gs,
                           tp1 = 'Baseline',
                           tp = 'On nivo')
}), fill = T)

invisible(m[p_val > .05, p_val := NA])
p <- plot_p_values_induction(m)
print(p)
ggsave(plot = p, filename = file.path(plot_dir,
                            'induction_fc_p_values_baseline_on_nivo.png'),
       width = 10, height = 13, units = 'cm')
```

```{r, warning=FALSE, echo=FALSE, fig.width = 9, fig.height = 12}
invisible(m[, p_val := NA])
pa <- plot_p_values_induction(filter(m, arm != 'All arms'))
print(pa)
ggsave(plot = pa, filename = file.path(plot_dir,
                            'induction_fc_p_values_baseline_on_nivo.png'),
       width = 10, height = 13, units = 'cm')
# ggsave(plot = p, filename = file.path(plot_dir,
#                             'induction_fc_p_values_baseline_on_nivo.png'),
#        width = 10, height = 13, units = 'cm')
```

