```{r, warning=FALSE, echo=FALSE}
source('R/init.R')
source('R/load_rna_dat.R')
devtools::load_all('~/libs/GSEAgenesets')
```

```{r, warning=FALSE, echo=FALSE}
plot_gene_set <- function(gs = NULL,
                          gene_symbols = c('TP53', 'ERBB2'),
                          gs_name = paste(gene_symbols, collapse = '_'),
                          cf_numbers = c(),
                          patients = c(),
                          induction_arms = c(),
                          timepoints = c('Baseline'),
                          var_thresh = 0,
                          log_transform = 'log2',
                          distfun = 'pearson',
                          hclustfun = 'average',
                          shuffle = F,
                          fn_extra = '') {

  ## Select CF numbers to plot
  cf_numbers <- Reduce(union,
    c(cf_numbers,
      rna_sample_annotation$cf_number[match(patients,
                        rna_sample_annotation$patient)],
      rna_sample_annotation$cf_number[match(induction_arms,
                        rna_sample_annotation$induction_arm)],
      rna_sample_annotation$cf_number[as.character(rna_sample_annotation$timepoint) %in% timepoints]))

  if (length(cf_numbers) < 2) {
    warningf('Too little samples selected: %d', length(cf_numbers))
    return(invisible())
  }

  ensgs <- rna_read_counts_ann[which(external_gene_id %in% gene_symbols),
                               ensembl_gene_id]
  p_dat <- 
    preprocess_rna(rna_read_counts_cpm, gs_genes = ensgs,
                   log_transform = 'log2', gene_normalisation = T,
                   var_thresh = NULL, symbol_var = NULL,
                   donor_ids = cf_numbers)
  gene_idx <- rna_read_counts_ann[, which(external_gene_id %in% gene_symbols)]
  rownames(p_dat) <- rna_read_counts_ann[gene_idx, external_gene_id]

  ann_dat <- 
    cbind(rna_sample_annotation[match(cf_numbers, 
                                      rna_sample_annotation[, cf_number]), 
                          .(timepoint, induction_arm, clinical_response)],
          patient_labels[match(cf_numbers, rna_sample_annotation[, cf_number]), 
                               .(efron_thisted_estimator, sample_clonality)])
 
  fn <- file.path('plots',
                  sprintf('heatmap%s%s%s%s%s%s%s.pdf',
                    sprintf('_%s', gs_name),
                    ifelse(is.null(timepoints) || is.na(timepoints),
                           '', sprintf('_%s', 
                                       paste(timepoints, collapse = '-'))),
                    ifelse(is.null(log_transform) || is.na(log_transform),
                           '', sprintf('_%s', log_transform)),
                    sprintf('_%s', hclustfun),
                    sprintf('_%s', distfun),
                    ifelse(length(fn_extra) > 1, sprintf('_%s', fn_extra), ''),
                    ifelse(shuffle, '-shuf', '')
                  ))

  NMF::aheatmap(p_dat,
                labRow = NULL,
                labCol = NULL,
                distfun = distfun,
                hclustfun = hclustfun,
                annCol = ann_dat,
                # annColors = ann_colors,
                filename = fn,
                main = simple_cap(paste0(tolower(gs_name), fn_extra)))
  sys_file_open(fn)
}

plot_gene_set(gs_name = 'CD4_cytokines', 
              gene_symbols = filter_gmt(gmt_pat = 'custom.bindea')[[2]],
              # timepoints = 'Baseline')
              # timepoints = 'On nivo')
              timepoints = 'Post-induction')
```

```{r, warning=FALSE, echo=FALSE}
plot_gene_set(gs_name = 'CD4_cytokines', 
              gene_symbols = filter_gmt(gmt_pat = 'gu')[[2]],
              # timepoints = 'Baseline')
              # timepoints = 'On nivo')
              timepoints = 'Post-induction')
```

```{r, warning=FALSE, echo=FALSE}
# plot_gene_set()
# devtools::load_all('~/libs/GSEAgenesets')
plot_gene_set(gs_name = 'CD4_TIL', 
              gene_symbols = filter_gmt(gmt_pat = 'gu', 
                                        gene_set_pat = 'TIL')[[1]],
              # timepoints = 'Baseline')
              # timepoints = 'On nivo')
              timepoints = 'Post-induction')
```

```{r, warning=FALSE, echo=FALSE}
rna_sample_annotation[cf_number == 'cf15169']
```
